### ISSUE TITLE
Consistent crashing while trying to add a comment

### ISSUE THREAD

**Issue by szopin** [accumulator/Quickddit#20] opened 2016-06-02 18:08 UTC
https://www.reddit.com/r/EliteDangerous/comments/4m71b8/whats_your_everyday_ship_in_21/d3t2qr2

Three times in a row, not sure if parent comment or the thread is the issue, but quickddit crashed three times on me on this one

**Comment by accumulator** [comment] 2016-06-03 06:49
thanks for reporting, but I cannot reproduce. It's unlikely to be related to the context, but instead the message contents you're trying to post..

**Comment by accumulator** [comment] 2016-06-13 17:10
I suspect this might be related to the rate limiter, which can reply with an error, which wasn't handled properly until commit 4b6b7e6e98d405e6c0eb95239b9ba6a567743abc

Can you confirm you were adding multiple comments in a short time when it happened?

**Comment by szopin** [comment] 2016-06-15 17:40
Yes, that must've been it, tried adding a comment there later and it didn't crash quickditt, so most likely this, nice catch!

**Comment by szopin** [comment] 2016-06-15 17:42
not sure how to edit on mobile, but just to add, I was changing the comment on each try, so crash-based-on-content is very unlikely, was just generic text, no links/formatting, must've been limit

**Comment by accumulator** [comment] 2016-06-16 06:41
ok, great! closing.

**Closed by accumulator** 2016-06-16 06:41 UTC
Labels: help wanted
